# Generated by Django 2.0.6 on 2019-01-15 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20190115_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=75)),
                ('service', models.CharField(max_length=150)),
                ('Eta', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('tracking_id', models.CharField(max_length=30)),
                ('payment', models.IntegerField()),
            ],
        ),
    ]
