# Generated by Django 2.0.6 on 2019-01-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField(max_length=10)),
                ('Comments', models.CharField(max_length=1000)),
                ('Details', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomStatus', models.BooleanField(default=False)),
            ],
        ),
    ]
