# Generated by Django 2.0.6 on 2019-01-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=15)),
                ('service', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
                ('token_no', models.IntegerField()),
            ],
        ),
    ]
